//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSelling2.DatenBank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsSellingEntities1 : DbContext
    {
        public CarsSellingEntities1()
            : base("name=CarsSellingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbCarsFoto> TbCarsFotoes { get; set; }
        public virtual DbSet<TbCarsInfo> TbCarsInfoes { get; set; }
        public virtual DbSet<TbOwnersInfo> TbOwnersInfoes { get; set; }
        public virtual DbSet<TbSellingInfo> TbSellingInfoes { get; set; }
    }
}
